version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    groups:
      "all-pip-dependencies":
        patterns:
        - "*"

  - package-ecosystem: "uv"
    directory: "/"
    allow:
      - dependency-name: "g4f*"
    schedule:
      interval: "daily"
