version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-name: "g4f*"
    groups:
      "all-pip-dependencies":
        patterns:
        - "*"
